[2025-05-25T12:37:35.117+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-25T12:37:35.145+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_d scheduled__2025-05-24T00:00:00+00:00 [queued]>
[2025-05-25T12:37:35.154+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_d scheduled__2025-05-24T00:00:00+00:00 [queued]>
[2025-05-25T12:37:35.154+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-25T12:37:35.166+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalPythonOperator): ext_py_d> on 2025-05-24 00:00:00+00:00
[2025-05-25T12:37:35.172+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=160) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T12:37:35.173+0000] {standard_task_runner.py:63} INFO - Started process 164 to run task
[2025-05-25T12:37:35.174+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_branch_operator', 'ext_py_d', 'scheduled__2025-05-24T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator.py', '--cfg-path', '/tmp/tmpp409h58q']
[2025-05-25T12:37:35.176+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask ext_py_d
[2025-05-25T12:37:35.226+0000] {task_command.py:426} INFO - Running <TaskInstance: example_branch_operator.ext_py_d scheduled__2025-05-24T00:00:00+00:00 [running]> on host af29f3c8a508
[2025-05-25T12:37:35.296+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_operator' AIRFLOW_CTX_TASK_ID='ext_py_d' AIRFLOW_CTX_EXECUTION_DATE='2025-05-24T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-24T00:00:00+00:00'
[2025-05-25T12:37:35.298+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-25T12:37:35.698+0000] {baseoperator.py:400} WARNING - ExternalPythonOperator.execute cannot be called outside TaskInstance!
[2025-05-25T12:37:35.777+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-callwrrb8yge/script.py /tmp/venv-callwrrb8yge/script.in /tmp/venv-callwrrb8yge/script.out /tmp/venv-callwrrb8yge/string_args.txt /tmp/venv-callwrrb8yge/termination.log
[2025-05-25T12:37:35.777+0000] {process_utils.py:187} INFO - Output:
[2025-05-25T12:37:38.037+0000] {process_utils.py:191} INFO - Hello World from external Python
[2025-05-25T12:37:38.351+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-25T12:37:38.351+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-25T12:37:38.360+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=example_branch_operator, task_id=ext_py_d, run_id=scheduled__2025-05-24T00:00:00+00:00, execution_date=20250524T000000, start_date=20250525T123735, end_date=20250525T123738
[2025-05-25T12:37:38.396+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-25T12:37:38.423+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-25T12:37:38.425+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
