[2025-05-25T12:37:35.168+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-25T12:37:35.194+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_a manual__2025-05-25T12:37:18.175203+00:00 [queued]>
[2025-05-25T12:37:35.204+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: example_branch_operator.ext_py_a manual__2025-05-25T12:37:18.175203+00:00 [queued]>
[2025-05-25T12:37:35.204+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-25T12:37:35.215+0000] {taskinstance.py:2330} INFO - Executing <Task(ExternalPythonOperator): ext_py_a> on 2025-05-25 12:37:18.175203+00:00
[2025-05-25T12:37:35.229+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=161) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-25T12:37:35.230+0000] {standard_task_runner.py:63} INFO - Started process 165 to run task
[2025-05-25T12:37:35.231+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'example_branch_operator', 'ext_py_a', 'manual__2025-05-25T12:37:18.175203+00:00', '--job-id', '14', '--raw', '--subdir', '/home/***/.local/lib/python3.12/site-packages/***/example_dags/example_branch_operator.py', '--cfg-path', '/tmp/tmpesipxcfm']
[2025-05-25T12:37:35.233+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask ext_py_a
[2025-05-25T12:37:35.271+0000] {task_command.py:426} INFO - Running <TaskInstance: example_branch_operator.ext_py_a manual__2025-05-25T12:37:18.175203+00:00 [running]> on host af29f3c8a508
[2025-05-25T12:37:35.340+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='example_branch_operator' AIRFLOW_CTX_TASK_ID='ext_py_a' AIRFLOW_CTX_EXECUTION_DATE='2025-05-25T12:37:18.175203+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-25T12:37:18.175203+00:00'
[2025-05-25T12:37:35.342+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-25T12:37:35.750+0000] {baseoperator.py:400} WARNING - ExternalPythonOperator.execute cannot be called outside TaskInstance!
[2025-05-25T12:37:35.833+0000] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python /tmp/venv-callmvll4ir6/script.py /tmp/venv-callmvll4ir6/script.in /tmp/venv-callmvll4ir6/script.out /tmp/venv-callmvll4ir6/string_args.txt /tmp/venv-callmvll4ir6/termination.log
[2025-05-25T12:37:35.834+0000] {process_utils.py:187} INFO - Output:
[2025-05-25T12:37:38.086+0000] {process_utils.py:191} INFO - Hello World from external Python
[2025-05-25T12:37:38.406+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-25T12:37:38.407+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-25T12:37:38.415+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=example_branch_operator, task_id=ext_py_a, run_id=manual__2025-05-25T12:37:18.175203+00:00, execution_date=20250525T123718, start_date=20250525T123735, end_date=20250525T123738
[2025-05-25T12:37:38.454+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-25T12:37:38.477+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-25T12:37:38.479+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
